services:
  - type: web
    name: kutabare-server
    env: node
    plan: free
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MONGODB_URI
        value: your-connection-string-here
      - key: BOT_TOKEN
        value: your-bot-token-here
    rootDir: server
